name: Bluesky Bot

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bot Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Bot Script
        env:
          BSKY_USER: ${{ secrets.BSKY_USER }}
          BSKY_PASS: ${{ secrets.BSKY_PASS }}
        run: node index.js
